#!/bin/bash 

JDK_HOME_BIN=/usr/java/jdk1.7.0_21/bin

if [ $# -ne 1 ]
then
        echo " usage `basename $0` PID"
        exit 0
fi

PID=$1
cd $JDK_HOME_BIN

./jstack -l $PID > /dev/null 2>&1

if [  $? -eq 0 ]
then
        OPTIONIS="-l"
else
        OPTIONIS="-F"
fi

MYCOUNT=0

while [ $MYCOUNT -ne '10' ]
do
MYCOUNT=`eval expr '$MYCOUNT + 1'`
echo "processing interation number $MYCOUNT"
./jstack $OPTIONIS  $PID > /tmp/jstack.$MYCOUNT.txt
echo "------------- End of jstack -------------" >> /tmp/jstack.$MYCOUNT.txt
ps -eLf >> /tmp/jstack.$MYCOUNT.txt
echo "------------- End of ps  -------------" >> /tmp/jstack.$MYCOUNT.txt

sleep 10
done;

cd /tmp
tar -cvf ToMcc-jstack.tar jstack*

echo "End of generation of jstack"
echo " "
echo "send by mail file named /tmp/ToMcc-jstack.tar at the following email's address : support@mcc-soft.com"

